<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSfWrzEo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSfWrzEo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSfWrzEo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSfWrzEo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSfWrzEo\App_KernelDevDebugContainer([
    'container.build_hash' => 'SfWrzEo',
    'container.build_id' => 'd4aae509',
    'container.build_time' => 1712247575,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSfWrzEo');
