<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container84EYnip\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container84EYnip/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container84EYnip.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container84EYnip\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container84EYnip\App_KernelDevDebugContainer([
    'container.build_hash' => '84EYnip',
    'container.build_id' => '2f900ad7',
    'container.build_time' => 1712352512,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container84EYnip');
